### ISSUE TITLE
Bulk Scan-In v1.8 help

### ISSUE THREAD

**Issue by nica2022** [ExLibrisGroup/Cloud-app-multi-scan-in#10]
Since the new version (v1.8) of Bulk Scan-In, I cannot use the down arrow to select a Department or the Work order type. I have cleared my cache and tested two different browsers without success. Could I get some help?

**Comment by ori229** [comment]
Hi,
Can you give some more info? A screenshot? What institution code?
Thanks,
Ori
Alma Dev.

**Comment by nica2022** [comment]
The screenshots below show a new version (v1.8) of the Bulk Scan-In. The Before was one of my steps to remove work orders, but Now (with the new version), I cannot select our AcqDeptH-TML and our AcqWorkOrder (I do not get any options-it's blank). My last use of the Bulk Scan-in before starting having problems was on Jan 11, 2024. My institution code is LRU.

Many thanks!

Maria

***@***.***

**Comment by ori229** [comment]
The attachments didn't go through - can you attach them again please (via github.com)?
What is the URL of your Alma?
Does your Alma user have the Fulfillment Administrator role?

**Comment by nica2022** [comment]
Hello,

Attached is the screenshot. I'm not an Administrator, but my supervisor gives me some access to Fulfillment, and there were no recent changes to my roles (just the new version of the Bulk Scan-in).

Here is our URL:
https://tulane.alma.exlibrisgroup.com/mng/login?auth=SAML


Thanks,

Maria

***@***.***

María Gulden | Library Associate - Outsourcing and Cataloging
Tulane University Libraries<https://library.tulane.edu/> - Technical Services
7001 Freret St, New Orleans, LA 70118<https://www.bing.com/maps/?v=2&where1=7001+Freret+St%2C+New+Orleans%2C+LA+70118&FORM=BMAdIn&cp=29.939893~-90.122255&lvl=17.0>
***@***.******@***.***>
504-865-5696 | Fax: 504-862-5556

**Comment by ori229** [comment]
To populate the dropdown, the Cloud App calls the Get-Departments API.
The API is currently only allowed for FULFILL_ADMINISTRATION privilege. We'll try to fix that, but in the meantime, please add the Fulfillment Administrator role to your user and it should work.

**Comment by GenaGeorge** [comment]
This seems to have changed from the previous version.  We have had staff without the Fulfill_Administration privilege using the Bulk Scan-In app for a while.  Feels like a step backwards, requiring only high-level privilege holders to do routine bulk item changes.  Is that the only workaround at this time?

Gena George
Tulane University Libraries

**Comment by ori229** [comment]
We pushed a new release of the Cloud App - it should fix it (if the API request is not allowed it will fall back to a regular textbox) - please try and let me know if you still have any issue

**Comment by nica2022** [comment]
Hello,
Attached are the tests I did this morning with the updated version 2.0. I also added screenshots of what I could do before with the Bulk Scan-In. I was able to enter the Department, but I still cannot use the Work order type.  Thanks so much for your help!
[Bulk Scan In problems.pdf](https://github.com/ExLibrisGroup/Cloud-app-multi-scan-in/files/14040534/Bulk.Scan.In.problems.pdf)

**Comment by ori229** [comment]
Amm... how about now? (New release created 5 minutes ago)

**Comment by nica2022** [comment]
Thank you, Ori!! It works now.
