### ISSUE TITLE
Not able to save configurations at Institution Level Version: v1.8|Last updated on 18 Jan 2024

### ISSUE THREAD

**Issue by jbgarris** [ExLibrisGroup/Cloud-app-multi-scan-in#11]
With the new version (Version: v1.8), we are no longer able to save configurations when setting the "Library *" to "Institution Level." We can save configurations when an actual library is selected. 

Link to what we are seeing: https://www.awesomescreenshot.com/video/24297868?key=17651b7dab80a361ab9eb2d259eb3daa

Josh Garris
University of South Carolina Libraries

**Comment by ori229** [comment]
Fixed with Release https://github.com/ExLibrisGroup/Cloud-app-multi-scan-in/releases/tag/v2.0
