### ISSUE TITLE
Scanning in an item as Done thats not In Process puts Item back In Process

### ISSUE THREAD

**Issue by kfeeken** [ExLibrisGroup/Cloud-app-multi-scan-in#12]
We noticed that when we have the Bulk Scan In Cloud App configured to Set In Process items to Done, if we include an item to be scanned that is not currently In Process, after running the scan it will set that item a Process Type of In Process.  Ideally we would not be scanning items as Done that aren't In Process, but our staff occasionally make a mistake and include items that have already had their work order finalized.  
I tested this behavior in Alma, if I scan an item as Done at a work order desk, and the item is not currently in Process, Alma either puts the item in transit to its owning library or directs it to be reshelved.  
Ideally the Cloud App would behave the same as Alma and not scan these items back into the work order department.

**Comment by ori229** [comment]
This seems like an issue with the API (and not with the Cloud App) so if you open a Salesforce case, it could be enhanced/fixed.
