### ISSUE TITLE
Error message for status

### ISSUE THREAD

**Issue by tabusch** [ExLibrisGroup/Cloud-app-multi-scan-in#14]
I have a work order type of Collection Maintenance configured at the library level for a Collection Maintenance Department. I have 4 statuses configured for the Collection Maintenance work order type: Search1, Search2, Search3, and Review. Everything appears to be set up correctly, but when I scan a barcode file, I get the following error for each barcode: “Info: The parameter 'status' has no valid options, and therefore the sent value 'Search1' is invalid.” What do I have configured wrong? I hope the screenshots help.

![AppErrors](https://github.com/user-attachments/assets/b1fba76d-8167-4d26-a55f-c9450e5f0494)
![AppSettings](https://github.com/user-attachments/assets/b08283f1-e623-4b06-bd00-8c20efe5e2ce)
![StatusConfiguration](https://github.com/user-attachments/assets/3e774dc8-a2d8-404b-af96-61adecf36de1)

**Comment by ori229** [comment]
The issue here was in the underlying Alma API. It is planned to be fixed in Dec 2024 Release

**Comment by tabusch** [comment]
Hi. The scan-in app worked for me in early December before I left for winter break in late December. Now, I am getting the same error as I originally posted about when trying to add a status. Do you know why this might be?

**Comment by ori229** [comment]
Please give it a try after Jan Release is installed (Jan 12)
