### ISSUE TITLE
The "circ desk" field is unclear

### ISSUE THREAD

**Issue by jweisman** [ExLibrisGroup/Cloud-app-multi-scan-in#2]
(From Yoel)

1. I think in the pop up below for the circ desk it should state whether the code or the name should be entered.
2. Can we make it a pull down box which will bring all circ desks of the Library already chosen above?
3. I think we should call it "Circulation Desk" instead of circ_desk.

![image001](https://user-images.githubusercontent.com/80420/111157081-201d0880-859f-11eb-8cb9-dc4298e3a4b8.png)

**Comment by liron58** [comment]
Hi,

Thanks for the feedback.
1 & 3 got fixed in the new version and should be available soon.
Regarding 2, currently, it's not possible were working on that and it will be implemented a few months from now.

**Comment by ori229** [comment]
Internal code: URM-160686
