### ISSUE TITLE
Add option to change status

### ISSUE THREAD

**Issue by cbaksik** [ExLibrisGroup/Cloud-app-multi-scan-in#3]
Hi Josh - it would be hugely helpful to have an option to change work order status through this tool. Due to COVID, we have a backlog of thousands and thousands of materials, many of which were received remotely while people are at home. Many of these need to change status (they're in the Acq work order) to reflect that they are in the Cataloging department, so that Cat staff know what they need to work on (much of their work is happening remotely as well right now). Because of the quantity of material, scanning in one at a time to change status isn't feasible. It would be so valuable to use this app to change work order status in addition to its other very useful features. 

Thank you for whatever you can do to make this happen!

Best,
Corinna (Harvard)

**Comment by jweisman** [comment]
Hi @cbaksik - thanks for your suggestion. It seems like this is possible. We will try to add this in the near future.

**Comment by liron58** [comment]
Hi @cbaksik . We have added a status field in the settings menu, It will be available in the cloud app soon.

**Comment by cbaksik** [comment]
😀 

Fantastic!!!!
