### ISSUE TITLE
Scan for institution level department?

### ISSUE THREAD

**Issue by WilliamDWalsh** [ExLibrisGroup/Cloud-app-multi-scan-in#4]
Hi, Is it possible to use this app to scan at an institution level department? If not, could you consider as an enhancement? Thanks, Bill

**Comment by ori229** [comment]
The Cloud App is based on the API documented here: https://developers.exlibrisgroup.com/alma/apis/docs/bibs/UE9TVCAvYWxtYXdzL3YxL2JpYnMve21tc19pZH0vaG9sZGluZ3Mve2hvbGRpbmdfaWR9L2l0ZW1zL3tpdGVtX3BpZH0=/
The library field is mandatory, so even if you have a department that serves the whole institution you'll still need to configure a library.
Makes sense?

**Comment by WilliamDWalsh** [comment]
It does--thank you for confirming. Bill

**Comment by gpeterso** [comment]
Hi @ori229 , 

Someone at my institution just asked me about adding this feature. The [scan-in API](https://developers.exlibrisgroup.com/alma/apis/docs/bibs/UE9TVCAvYWxtYXdzL3YxL2JpYnMve21tc19pZH0vaG9sZGluZ3Mve2hvbGRpbmdfaWR9L2l0ZW1zL3tpdGVtX3BpZH0=/) does allow institution-level department scanning. The documentation is a little unclear, but the API technically requires either `library` + `circ_desc` parameters *or* a `department` parameter. 

Could this issue be reopened?

Thank you, 
Jeff

**Comment by timothyprettyman** [comment]
I second this--it would be very helpful for us to be able to use the bulk scan-in cloud app for institution-level department scanning. 

-Tim (University of Michigan)

**Comment by ori229** [comment]
Reopening.  I'll add another option to the library drop-down:
![image](https://user-images.githubusercontent.com/139582/142865568-8b69acf9-2bb7-422d-9b73-9de33ae8b4fc.png)

**Comment by ori229** [comment]
Done - https://github.com/ExLibrisGroup/Cloud-app-multi-scan-in/commit/1cf7683782b2e387b0833fc45139bbbeb55354a4
