### ISSUE TITLE
txt file

### ISSUE THREAD

**Issue by MerzinYVC** [ExLibrisGroup/Cloud-app-multi-scan-in#5]
Hi, 
I have a problem with txt file with the barcodes. I receive the message "No items found for barcode ..."
What does that mean "line separating between each barcode"?
Maybe can you send the example.

**Comment by ori229** [comment]
A simple text file should do it, with each barcode in a separate line.
![image](https://user-images.githubusercontent.com/139582/139709755-fc12c819-3786-4c18-b277-c255f5c8d3a4.png)

**Comment by MerzinYVC** [comment]
Thank you!
