### ISSUE TITLE
Is it possible to add a report to this app?

### ISSUE THREAD

**Issue by ChukG** [ExLibrisGroup/Cloud-app-multi-scan-in#6]
Could this app have a report added to it, something similar to Alma jobs? We'd like to use it but I would like to be able to see if all the check-ins are successful or have any messages with them.

thanks,

**Comment by ori229** [comment]
The app already has a report. Anything missing? Or perhaps the format isn't suitable?
![image](https://user-images.githubusercontent.com/139582/143694268-b0044f73-9242-4578-b33f-8db5fc29f36f.png)

**Comment by ChukG** [comment]
My apologies -- I tested this a couple of times in our sandbox and didn't get any result, it just checked the books in with nothing else displayed. I tried it today and I get a progress circle and then the report which is perfectly acceptable.

thank you!
