### ISSUE TITLE
Just grey background, no scanning in

### ISSUE THREAD

**Issue by ChukG** [ExLibrisGroup/Cloud-app-multi-scan-in#7]
Hello, trying to bulk scan 66 barcodes and I just get a blank grey screen in the cloud app (in the area where previous tests have displayed the results). Tried on Chrome and Safari on MacOS -- any suggestions?

**Comment by ChukG** [comment]
Tried again with only 3 barcodes, same issue.

**Comment by ChukG** [comment]
Tried again on Firefox, same thing, blank grey screen and items don't get checked in.

**Comment by ori229** [comment]
Hi, We are not able to reproduce the issue. Can you open the browser's dev-tool (F12) and try it when the console tab is displayed. Any error? Please attach a screenshot here.  Thanks!

**Comment by ChukG** [comment]
Hi, we ended up checking in our items manually, I will test it next time.
