### ISSUE TITLE
Default circulation desk missing from drop-down list for some library sites

### ISSUE THREAD

**Issue by chris-m-jones** [ExLibrisGroup/Cloud-app-multi-scan-in#8]
Although the library list is set up correctly with the newer drop-down options, we are not seeing the default circulation desk listed under all of the libraries, oddly. The ones displaying are reading room and personal delivery enabled desks, but not the default seemingly.

Have uninstalled/reinstalled but still missing in this app - this is not as useful as being able to enter in freetext the code of the circ desk as an alternative.

**Comment by ori229** [comment]
I would like to have a look - perhaps it is an issue with the Retrieve Circulation Desks API.
https://developers.exlibrisgroup.com/alma/apis/docs/conf/R0VUIC9hbG1hd3MvdjEvY29uZi9saWJyYXJpZXMve2xpYnJhcnlDb2RlfS9jaXJjLWRlc2tzLw==/

Can you give an example for a library for which you don't see all circ-desks for (and what is your Alma's URL)?

**Comment by ori229** [comment]
Hi Chris, 
I have investigated and indeed there was a bug with the Retrieve Circulation Desks API.
We'll fix it for Alma's Aug 2022 Release.
