### ISSUE TITLE
Error message when clicking on Settings

### ISSUE THREAD

**Issue by MeowMix20** [ExLibrisGroup/Cloud-app-multi-scan-in#9]
Hello,

Sorry for this basic question. But new to Cloud apps. When my co-worker is trying to use the Bulck Scan-In app she clicks the Settings link to add the Library field. But gets the error message "You are not authorized to perform the requested action". Is this an ALMA permissions problem? Any help is appreciated.

thank you!

**Comment by ori229** [comment]
Yes, that would be on Alma's side. The Cloud App calls Alma's APIs, and in this case, it's:
GET /conf/libraries 
GET /conf/libraries/X/circ-desks
(both are documented here: https://developers.exlibrisgroup.com/alma/apis/conf/)
These 2 APIs are allowed for users with the TABLE_CONFIG_FULL privilege (which is included in many roles, for example in "User Manager")

**Comment by enettifee** [comment]
Hi @ori229 - glad to see that this issue has an explanation, as our library is in migration and ran into this as well - I just want to note that none of the roles with TABLE_CONFIG_FULL are circulation operators, at least as of the 2024 release: "Producer Manager, Catalog Administrator, Exlibris - Support, Exlibris - Implementer, Work Order Operator, Fulfillment Services Manager, User Manager, Leganto Interface Administrator, General System Administrator, Repository Manager, Discovery - Admin, View Management, Preservation Analyst, Preservation Manager, Vendor Manager, Ledger Manager, Fund Manager, Receiving Operator Limited, Receiving Operator, Arranging Manager, License Manager, Configuration Manager, User Administrator, Fulfillment Administrator, Repository Administrator, Purchasing Manager, Acquisitions Administrator, Letter Administrator, Assessing Manager, Depositing Administrator." 

Libraries can figure this out and work with it, I think, but it's also worth trying to see if the underlying privilege can be added to Circulation Desk Operator, IMO.
